# Generated by Django 5.0.6 on 2024-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0002_userprofile_delete_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
